apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: pythonconsumer
          image: sivin20/pythonconsumer:latest
          ports:
            - containerPort: 80
